import type { Book } from './types';

const todayISO = () => new Date().toISOString().slice(0, 10);
const daysAgo = (n: number) => {
	const d = new Date();
	d.setDate(d.getDate() - n);
	return d.toISOString().slice(0, 10);
};
const daysFromNow = (n: number) => {
	const d = new Date();
	d.setDate(d.getDate() + n);
	return d.toISOString().slice(0, 10);
};

const aladinQuotes = (best: number, good: number, fair: number, checkedAt: string) => [
	{ provider: 'aladin', grade: '최상' as const, price: best, currency: 'KRW', availability: 'yes' as const, rawStatus: 'ok', checkedAt },
	{ provider: 'aladin', grade: '상' as const, price: good, currency: 'KRW', availability: 'yes' as const, rawStatus: 'ok', checkedAt },
	{ provider: 'aladin', grade: '중' as const, price: fair, currency: 'KRW', availability: 'yes' as const, rawStatus: 'ok', checkedAt }
];

export const sampleBooks: Book[] = [
	{
		id: 'b1',
		isbn: '9788937473135',
		title: '데미안',
		author: '헤르만 헤세',
		publisher: '민음사',
		publishedYear: 2009,
		price: 8500,
		category: '소설',
		condition: 'good',
		location: '거실 책장 A-1',
		purchasedUsed: false,
		purchasedPrice: 8500,
		reasonToKeep: '인생 책. 매년 다시 읽음',
		rereadIntent: 5,
		library: 'yes',
		millie: 'yes',
		ebook: 'yes',
		usedBuyback: 'yes',
		usedBuybackPrice: 1200,
		lastCheckedAt: daysAgo(5),
		buybackQuotes: aladinQuotes(1500, 1200, 900, daysAgo(5)),
		recommendation: 'keep',
		disposal: 'keep',
		sellStatus: 'none',
		scanStatus: 'none',
		discardStatus: 'none',
		highlights: [
			{
				id: 'h1',
				page: 123,
				quote: '새는 알을 깨고 나온다. 알은 세계다.',
				memo: '성장의 본질에 관한 문장.',
				tags: ['성장', '고전'],
				importance: 5
			}
		],
		addedAt: daysAgo(120)
	},
	{
		id: 'b2',
		isbn: '9788932917245',
		title: '사피엔스',
		author: '유발 하라리',
		publisher: '김영사',
		publishedYear: 2015,
		price: 22000,
		category: '인문',
		condition: 'fair',
		location: '서재 B-2',
		rereadIntent: 2,
		library: 'yes',
		millie: 'yes',
		ebook: 'yes',
		usedBuyback: 'yes',
		usedBuybackPrice: 4500,
		lastCheckedAt: daysAgo(10),
		buybackQuotes: aladinQuotes(5200, 4800, 4500, daysAgo(10)),
		recommendation: 'sell',
		disposal: 'sell',
		sellStatus: 'ready',
		scanStatus: 'none',
		discardStatus: 'none',
		highlights: [],
		addedAt: daysAgo(200)
	},
	{
		id: 'b3',
		isbn: '9788954682152',
		title: '총, 균, 쇠',
		author: '재레드 다이아몬드',
		publisher: '문학사상사',
		publishedYear: 2013,
		price: 25000,
		category: '인문',
		condition: 'good',
		location: '서재 B-3',
		rereadIntent: 1,
		library: 'yes',
		millie: 'no',
		ebook: 'yes',
		usedBuyback: 'yes',
		usedBuybackPrice: 5800,
		lastCheckedAt: daysAgo(45),
		buybackQuotes: aladinQuotes(6800, 6200, 5800, daysAgo(45)),
		recommendation: 'scan',
		disposal: 'scan',
		sellStatus: 'none',
		scanStatus: 'ready',
		discardStatus: 'none',
		scanPurpose: 'guillotine',
		highlights: [{ id: 'h3', page: 56, quote: '지리적 요인이 문명의 흥망을 결정했다.', tags: ['역사'], importance: 4 }],
		addedAt: daysAgo(150)
	},
	{
		id: 'b4',
		isbn: '9788937834790',
		title: '1Q84 1',
		author: '무라카미 하루키',
		publisher: '문학동네',
		publishedYear: 2009,
		price: 13800,
		category: '소설',
		condition: 'marked',
		location: '거실 책장 A-3',
		rereadIntent: 3,
		library: 'yes',
		millie: 'yes',
		ebook: 'yes',
		usedBuyback: 'no',
		lastCheckedAt: daysAgo(2),
		recommendation: 'review',
		disposal: 'review',
		sellStatus: 'none',
		scanStatus: 'none',
		discardStatus: 'none',
		reviewDate: todayISO(),
		highlights: [],
		addedAt: daysAgo(60)
	},
	{
		id: 'b5',
		isbn: '9788960516373',
		title: '함께 자라기',
		author: '김창준',
		publisher: '인사이트',
		publishedYear: 2018,
		price: 12000,
		category: '자기계발',
		condition: 'good',
		location: '서재 B-1',
		rereadIntent: 4,
		library: 'no',
		millie: 'no',
		ebook: 'no',
		usedBuyback: 'yes',
		usedBuybackPrice: 3200,
		lastCheckedAt: daysAgo(60),
		recommendation: 'keep',
		disposal: 'keep',
		sellStatus: 'none',
		scanStatus: 'none',
		discardStatus: 'none',
		highlights: [{ id: 'h4', page: 22, quote: '함께 자라는 사람들이 멀리 간다.', tags: ['성장', '팀'], importance: 5 }],
		addedAt: daysAgo(80)
	},
	{
		id: 'b6',
		isbn: '9788932473901',
		title: '팩트풀니스',
		author: '한스 로슬링',
		publisher: '김영사',
		publishedYear: 2019,
		price: 19800,
		category: '사회',
		condition: 'good',
		location: '서재 B-2',
		rereadIntent: 1,
		library: 'yes',
		millie: 'yes',
		ebook: 'yes',
		usedBuyback: 'yes',
		usedBuybackPrice: 6000,
		lastCheckedAt: daysAgo(40),
		recommendation: 'sell',
		disposal: 'undecided',
		sellStatus: 'none',
		scanStatus: 'none',
		discardStatus: 'none',
		highlights: [],
		addedAt: daysAgo(90)
	},
	{
		id: 'b7',
		isbn: '9788932473902',
		title: '넛지',
		author: '리처드 탈러',
		publisher: '리더스북',
		publishedYear: 2018,
		price: 17000,
		category: '경제',
		condition: 'poor',
		location: '창고',
		rereadIntent: 1,
		library: 'no',
		millie: 'no',
		ebook: 'no',
		usedBuyback: 'no',
		lastCheckedAt: daysAgo(35),
		recommendation: 'discard',
		disposal: 'undecided',
		sellStatus: 'none',
		scanStatus: 'none',
		discardStatus: 'none',
		highlights: [],
		addedAt: daysAgo(400)
	},
	{
		id: 'b8',
		isbn: '9788970127200',
		title: '어린 왕자',
		author: '생텍쥐페리',
		publisher: '열린책들',
		publishedYear: 2015,
		price: 9500,
		category: '소설',
		condition: 'mint',
		location: '거실 책장 A-1',
		rereadIntent: 5,
		library: 'yes',
		millie: 'yes',
		ebook: 'yes',
		usedBuyback: 'yes',
		usedBuybackPrice: 2000,
		lastCheckedAt: daysFromNow(0),
		recommendation: 'keep',
		disposal: 'keep',
		sellStatus: 'none',
		scanStatus: 'none',
		discardStatus: 'none',
		highlights: [],
		addedAt: daysAgo(10)
	}
];

