substitutions:
  _ENABLE_CLOUD_BUILD: "false"
  _ENABLE_ARTIFACT_REGISTRY: "false"
  _REGION: asia-northeast3
  _AR_REPO: personal-hub-repo
  _SERVICE: personal-hub

steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -f
      - Dockerfile.cloudrun
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
    waitFor:
      - build

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
